### ISSUE TITLE
Getting image signature should not appears as ERROR in log

### ISSUE THREAD

**Issue by lgranie** [lexemmens/podman-maven-plugin#93]
Hi,

IMHO, the plugin generates log about related to registry (get, push) in the wrong log level.

For exemple : 
10:18:16  [INFO] Pushing image: quay.io/xxx/yyyy to quay.io
10:18:16  **[ERROR]** Getting image source signatures
10:18:16  **[ERROR]** Copying blob sha256:tralalatsouintsouin
[...]
10:18:19  **[ERROR]** Writing manifest to image destination
10:18:20  **[ERROR]** Storing signatures

or :
10:09:57  **[ERROR]** Getting image source signatures
10:09:57  **[ERROR]** Copying blob sha256:abracadabra
[...]
10:10:05 **[ERROR]** Copying config sha256:magie

**Comment by lexemmens** [comment]
Thanks for your issue. If I remember correctly, these log messages are written by Podman to stderr, hence the Podman Maven Plugin will therefore also print them as error. 

Although I agree it is strange, I am hesitant to change this in the `podman-maven-plugin`, because it would mean that there should only be an exception for these specific log lines (real errors should still be logged as error) whilst this is primarily a responsibility of Podman itself.
